import { Box, Link, Stack } from '@mui/material'
import { styled } from '@mui/system'
import React from 'react'

import { wfRepo } from '@/envDefault'

const SecondaryLink = styled(Link)(({ theme }) => ({
  color: theme.palette.secondary.main,
  fontWeight: 'bold',
}))

interface Props {
  sx?: object
}

const Hero: React.VFC<Props> = (props: Props) => {
  return (
    <Box
      sx={{
        bgcolor: 'primary.main',
        maxWidth: '100vw',
        ...props.sx,
      }}>
      <Box
        sx={{
          maxWidth: 'lg',
          mx: 'auto',
          p: 4,
        }}>
        <Stack spacing={2}>
          <Box
            children={wfRepo()}
            component='h1'
            sx={{
              color: 'common.white',
              fontFamily: 'Quicksand',
              fontSize: '3.6rem',
              fontWeight: 'bold',
              my: 0,
            }}
          />
          <Box
            component='p'
            sx={{
              fontFamily: 'Quicksand',
              fontSize: '1.2rem',
            }}>
            This app is generated by{' '}
            <SecondaryLink
              children={'ddbj/yevis-web'}
              href='https://github.com/ddbj/yevis-web'
              target='_blank'
              underline='hover'
            />
            .
            <br />
            Browse workflows delivered by the{' '}
            <SecondaryLink
              children={'GA4GH Tool Registry Service API'}
              href='https://www.ga4gh.org/news/tool-registry-service-api-enabling-an-interoperable-library-of-genomics-analysis-tools/'
              target='_blank'
              underline='hover'
            />
            ,
            <br />
            which is generated by{' '}
            <SecondaryLink
              children={'ddbj/yevis-cli'}
              href='https://github.com/ddbj/yevis-cli'
              target='_blank'
              underline='hover'
            />{' '}
            and hosted on{' '}
            <SecondaryLink
              children={wfRepo()}
              href={`https://github.com/${wfRepo()}`}
              target='_blank'
              underline='hover'
            />
            .
          </Box>
        </Stack>
      </Box>
    </Box>
  )
}

export default Hero
