import { Box, Link, Stack } from '@mui/material'
import React from 'react'

import { wfRepo } from '@/envDefault'

interface SecondaryLinkProps {
  href: string
  label: string
}

const SecondaryLinkComponent: React.VFC<SecondaryLinkProps> = (
  props: SecondaryLinkProps
) => {
  return (
    <Link
      children={props.label}
      href={props.href}
      sx={{
        color: 'secondary.main',
        fontWeight: 'bold',
      }}
      target='_blank'
      underline='hover'
    />
  )
}

const SecondaryLink = React.memo(SecondaryLinkComponent)

interface Props {
  sx?: object
}

const Hero: React.VFC<Props> = (props: Props) => {
  return (
    <Box
      sx={{
        bgcolor: 'primary.main',
        maxWidth: '100vw',
        ...props.sx,
      }}>
      <Box
        sx={{
          maxWidth: 'lg',
          mx: 'auto',
          p: 4,
        }}>
        <Stack spacing={2}>
          <Box
            children={wfRepo()}
            component='h1'
            sx={{
              color: 'common.white',
              fontFamily: 'Quicksand',
              fontSize: '3.6rem',
              fontWeight: 'bold',
              my: 0,
            }}
          />
          <Box
            component='p'
            sx={{
              fontFamily: 'Quicksand',
              fontSize: '1.2rem',
            }}>
            This app is generated by{' '}
            <SecondaryLink
              href='https://github.com/ddbj/yevis-web'
              label={'ddbj/yevis-web'}
            />
            .
            <br />
            Browse workflows delivered by the{' '}
            <SecondaryLink
              href='https://www.ga4gh.org/news/tool-registry-service-api-enabling-an-interoperable-library-of-genomics-analysis-tools/'
              label={'GA4GH Tool Registry Service API'}
            />
            ,
            <br />
            which is generated by{' '}
            <SecondaryLink
              href='https://github.com/ddbj/yevis-cli'
              label={'ddbj/yevis-cli'}
            />{' '}
            and hosted on{' '}
            <SecondaryLink
              href={`https://github.com/${wfRepo()}`}
              label={wfRepo()}
            />
            .
          </Box>
        </Stack>
      </Box>
    </Box>
  )
}

export default React.memo(Hero)
