import Box from '@mui/material/Box'
import Link from '@mui/material/Link'
import Stack from '@mui/material/Stack'
import React from 'react'

const MainHero: React.VFC = () => {
  return (
    <Box
      sx={{
        maxWidth: '100vw',
        height: '300px',
        bgcolor: 'primary.main',
      }}>
      <Box
        sx={{
          maxWidth: 'lg',
          mx: 'auto',
          py: 2,
          px: 8,
        }}>
        <Stack>
          <Box
            sx={{
              typography: 'h2',
              color: 'white',
              fontWeight: 'bold',
              fontFamily: 'Quicksand',
              my: 4,
            }}
            component='h1'>
            ddbj/yevis-workflows
          </Box>
          <Box
            sx={{
              typography: 'subtitle1',
              fontFamily: 'Quicksand',
              fontSize: '1.2rem',
            }}>
            This app is generated by{' '}
            <Link
              sx={{
                color: 'secondary.main',
                fontWeight: 'bold',
              }}
              href='https://github.com/ddbj/yevis-web'>
              ddbj/yevis-web.
            </Link>
            <br />
            Browse workflows delivered by the{' '}
            <Link
              sx={{
                color: 'secondary.main',
                fontWeight: 'bold',
              }}
              href='https://www.ga4gh.org/news/tool-registry-service-api-enabling-an-interoperable-library-of-genomics-analysis-tools/'>
              GA4GH TRS API
            </Link>
            ,
            <br />
            which is generated by{' '}
            <Link
              sx={{
                color: 'secondary.main',
                fontWeight: 'bold',
              }}
              href='https://github.com/ddbj/yevis-cli'>
              ddbj/yevis-cli
            </Link>{' '}
            and hosted on{' '}
            <Link
              sx={{
                color: 'secondary.main',
                fontWeight: 'bold',
              }}
              href='https://github.com/ddbj/yevis-workflows'>
              ddbj/yevis-workflows
            </Link>
            .
          </Box>
        </Stack>
      </Box>
    </Box>
  )
}

export default MainHero
